services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - .env
    image: journalguide-frontend:latest
    container_name: journalguide-frontend
    volumes:
      - ./client:/app           # Mount local code for hot reload
      - /app/node_modules       # Avoid overwriting node_modules
    command: npm run dev

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-5001}:5001"
    env_file:
      - .env
    image: journalguide-backend:latest
    container_name: journalguide-backend
